name: Build ARM64 DEB Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: yourusername/yourimage:latest
        build-args: |
          VERSION=latest
        platforms: linux/arm64

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y <your-package-dependencies-here>

    - name: Build DEB package
      run: dpkg-deb --build --root-owner-group <source-directory> <deb-package-name>.deb

    - name: Upload DEB package to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./<deb-package-name>.deb
        asset_name: <deb-package-name>.deb
        asset_content_type: application/vnd.debian.binary-package
