name: Build ARM64 DEB Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y <your-package-dependencies-here>

    - name: Build DEB package
      run: dpkg-deb --build --root-owner-group . com.34306.adspeed_1.0_iphoneos-arm.deb

    - name: Upload DEB package to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./com.34306.adspeed_1.0_iphoneos-arm.deb
        asset_name: com.34306.adspeed_1.0_iphoneos-arm.deb
        asset_content_type: application/vnd.debian.binary-package
